@startuml
title Котировочная сессия (КС) + Smart Service - Схема процесса BPMN

|#Lavender|AI/ML НМЦК Сервис|
|#FloralWhite|Система (Портал)|
|#LightGreen|Поставщик|

|Заказчик|
start
:Создать черновик КС;
:Добавить позиции в спецификацию;

|AI/ML НМЦК Сервис|
:Автоматизированный расчет и обоснование НМЦК;
note right: См. отдельную схему алгоритма сервиса

|Заказчик|
if (Пользователь согласен с ценой?) then (нет)
    :Редактировать цену вручную;
else (да)
endif
:Указать длительность КС (3/6/24 ч);
:Опубликовать КС с обоснованием;

|Система (Портал)|
:Запустить таймер торгов;
:Активировать КС;

|Поставщик|
repeat
    :Просмотреть требования и обоснование НМЦК;
    :Подать ценовое предложение (ставку);
    
    |Система (Портал)|
    if (Ставка за последние 5 минут?) then (да)
        :Активировать переторжку (+5 мин);
    else (нет)
    endif
backward:Следующий участник;
repeat while (Таймер активен?) is (да)

|Система (Портал)|
:Определить победителя;
stop
@enduml
