@startuml
title Прямая закупка + Smart Service - Схема процесса BPMN

|#Lavender|AI/ML НМЦК Сервис|
|#FloralWhite|Система (Портал)|
|#LightGreen|Поставщик|

|Заказчик|
start
:Поиск товара в каталоге СТЕ;
:Выбор конкретной оферты поставщика;

|AI/ML НМЦК Сервис|
:Анализ рыночных данных и формирование рекомендации;
note right: Диаграмма "Алгоритм работы Смарт-сервиса"

|Заказчик|
:Добавление оферты в корзину;
:Создание заявки на прямую закупку;
:Заполнение этапов поставки;
:Направить заявку поставщику;

|Система (Портал)|
:Установить статус: "Новая";

|Поставщик|
if (Поставщик подтверждает?) then (да)
    :Подтвердить заявку;
    |Система (Портал)|
    :Сформировать проект контракта;
    |Заказчик|
    :Подписать контракт (ЭП);
    |Поставщик|
    :Подписать контракт (ЭП);
else (нет)
    :Отклонить заявку;
endif

stop
@enduml
